- name: gathering facts
  hosts: web
  become: yes
  tasks:
  - name: print the facts
    ansible.builtin.debug:
      msg: "{{ansible_facts}}"

  - name: install inginx
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"